### ISSUE TITLE
Refactor recompose/rx to components

### ISSUE THREAD

**Issue by AvivRubys** [Soluto/react-shisell#13]
In most cases, recompose/rx is only making these HOCs more complicated

- [x]  `withAnalyticOnMount` should just be a component, no reason for even using rx
- [x]  `withAnalyticOnEvent` can be much simpler if implemented as a plain component
- [x] Every place we use the `compose(withAnalytics, ..., withoutAnalytics)` pattern can probably be a simple component - `enrichAnalytics` for example
- [x] `withOnPropChangedAnalytic` can pretty much consist of an if statement inside `componentDidUpdate`

This has a few benefits:
* Code will be simpler and easier to read
* Less dependencies (important as this is a library)
* Easier to give proper TS types to

**Comment by AvivRubys** [comment]
API # 4 that came up from talking to @itaym2 is to give up completely on passing in props as analytics, but leave it all to the HOC definition, which leaves the underlying component's API intact:
```js
const MyButton = withAnalyticOnEvent({
    propName: 'onPress',
    analyticName: 'Click',
    mapPropsToExtras: (props) => ({Name: props.name}), // Optional
    mapPropsToIdentities: (props) => ({UserId: props.something}), // Optional
    shouldSendAnalytic: (e, props) => e.something && props.somethingElse, // Optional
})(Button);

const MyComponent = props => (
    <MyButton>
        My button
    </MyButton>
);
```

**Comment by itaym2** [comment]
Some thoughts:
1. maybe we should rename 'propName' to `eventName` or `event`?
2. We can infer the `analyticName` from the `propName` if `analyticName` is missing. For example, If `propName`  is `onEvent`, and the `analyticName` is null, we can automatically infer that the analyticName should be `Event`
3. I think we should rename shouldSendAnalytic. My suggestions are `shouldDispatch` or 'filter'

**Comment by AvivRubys** [comment]
1. `propName` was originally `eventName`, but this misrepresented what it actually did, which is inject/override a prop by that name. `propName` seems much easier to undestand.
2. This seems like way too much magic to me - reading the HOC can leave you confused about what it does, I think verbosity is preferred over that.
3. Yeah, I think so as well. It used to be just `predicate`, but like `filter` I think that misses some context, I like `shouldDispatch`

**Comment by itaym2** [comment]
1. I find propName more confusing, we should get some more opinions about it
2. ok

**Comment by zoharlevin** [comment]
been following your discussion so i'll add an opinion about the `propName`:  i agree with @itaym2 , i think it's more confusing than `eventName`.  maybe `eventHandlerName`?

**Comment by AvivRubys** [comment]
On the whole I like API # 4 the best, and it's the current approach I've taken in my branch, but I see some issues with it.
It's susceptible to the same issues we didn't like about HOCs relying on specific props existing, just like `mapTechIdToTimelineItems` and such.
It also forces you to not do any "calculations" inside your render, but do it exclusively in `mapProps` and such in case you need them in props, which can complicate your code.
I think the most readable&simple option would be # 2 or # 3

**Comment by itaym2** [comment]
But this is the point of this the HOC - taking props and adding them to the dispatched event. It's explicit (you choose which props to use), which makes it different from HOCs like `mapTechIdToToTimelineItems` which implicitly depend on an existing prop (you basically can't know it without looking at the source code)
